#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# deploy-droplet.sh - Bootstrap a fresh Ubuntu droplet for meWeb
# =============================================================================
# Installs Docker, configures the firewall, clones the repo, writes the .env,
# and starts the production stack. Designed for curl | bash usage:
#
#   curl -fsSL https://raw.githubusercontent.com/darrylcauldwell/meWeb/main/scripts/deploy-droplet.sh \
#     | bash -s -- [SITE_ADDRESS] [ACME_EMAIL] [REPO_URL]
#
# All arguments are optional - sensible defaults are baked in.
# Override any value by passing positional arguments.
#
# Idempotent - safe to re-run on an already-provisioned droplet.
# Tested on Ubuntu 22.04 / 24.04.
# =============================================================================

DEPLOY_DIR="/opt/meWeb"

usage() {
  cat <<EOF
Usage: deploy-droplet.sh [SITE_ADDRESS] [ACME_EMAIL] [REPO_URL]

  SITE_ADDRESS  Domain name         (default: blog.dreamfold.dev)
  ACME_EMAIL    Let's Encrypt email (default: darrylcauldwell@users.noreply.github.com)
  REPO_URL      Git clone URL       (default: https://github.com/darrylcauldwell/meWeb.git)

All arguments are optional. Run with --help to see this message.
EOF
  exit 0
}

log() {
  echo "[deploy] $*"
}

# ---------------------------------------------------------------------------
# 1. Resolve inputs (defaults baked in, overridable via positional args)
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
fi

SITE_ADDRESS="${1:-blog.dreamfold.dev}"
ACME_EMAIL="${2:-darrylcauldwell@users.noreply.github.com}"
REPO_URL="${3:-https://github.com/darrylcauldwell/meWeb.git}"

log "SITE_ADDRESS = $SITE_ADDRESS"
log "ACME_EMAIL   = $ACME_EMAIL"
log "REPO_URL     = $REPO_URL"

# ---------------------------------------------------------------------------
# 2. Install Docker
# ---------------------------------------------------------------------------
log "Installing Docker and Docker Compose plugin..."
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-v2

# ---------------------------------------------------------------------------
# 3. Enable Docker
# ---------------------------------------------------------------------------
log "Enabling Docker service..."
systemctl enable --now docker

# ---------------------------------------------------------------------------
# 4. Configure firewall
# ---------------------------------------------------------------------------
log "Configuring firewall..."
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
log "Firewall status:"
ufw status

# ---------------------------------------------------------------------------
# 5. Clone repo (or pull if already present)
# ---------------------------------------------------------------------------
if [[ -d "$DEPLOY_DIR/.git" ]]; then
  log "Repository already exists at $DEPLOY_DIR, pulling latest changes..."
  git -C "$DEPLOY_DIR" pull
else
  log "Cloning repository into $DEPLOY_DIR..."
  git clone "$REPO_URL" "$DEPLOY_DIR"
fi

# ---------------------------------------------------------------------------
# 6. Write .env
# ---------------------------------------------------------------------------
ENV_FILE="$DEPLOY_DIR/site/.env"
log "Writing $ENV_FILE..."
cat > "$ENV_FILE" <<ENVEOF
# Generated by deploy-droplet.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit these values to suit your deployment.

SITE_ADDRESS=${SITE_ADDRESS}
ACME_EMAIL=${ACME_EMAIL}
GITHUB_USER=darrylcauldwell
NTFY_ADDRESS=ntfy.dreamfold.dev
NTFY_URL=https://ntfy.dreamfold.dev
ENVEOF

# ---------------------------------------------------------------------------
# 7. Start the production stack
# ---------------------------------------------------------------------------
log "Starting production stack..."
cd "$DEPLOY_DIR/site"
docker compose -f docker-compose.production.yml up -d --build

# ---------------------------------------------------------------------------
# 8. Verify
# ---------------------------------------------------------------------------
log "Waiting for containers to start..."
sleep 5

log "Container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

# Check health endpoint (allow failure - cert may not be ready yet)
log "Checking health endpoint..."
if curl -sf --max-time 10 "http://localhost/healthz" > /dev/null 2>&1; then
  log "Health check passed."
else
  log "Health endpoint not yet reachable (this is normal if DNS is not configured yet)."
fi

# ---------------------------------------------------------------------------
# 9. Next steps
# ---------------------------------------------------------------------------
cat <<EOF

========================================
  Deployment complete!
========================================

Next steps:

  1. Ensure DNS A records point to this droplet's IP address:
       - ${SITE_ADDRESS}
       - ntfy.dreamfold.dev

  2. Once DNS propagates, Caddy will automatically obtain TLS certificates.
     Monitor certificate acquisition with:

       docker logs site

  3. Verify the site is live:

       curl -I https://${SITE_ADDRESS}
       curl https://${SITE_ADDRESS}/healthz
       curl -I https://ntfy.dreamfold.dev

  4. To update later:

       cd ${DEPLOY_DIR}/site
       git pull && docker compose -f docker-compose.production.yml up -d --build

EOF
