#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# deploy-droplet.sh - Bootstrap a fresh Ubuntu droplet for meWeb
# =============================================================================
# Installs Docker, configures the firewall, clones the repo, writes the .env,
# and starts the production stack. Designed for curl | bash usage:
#
#   curl -fsSL https://raw.githubusercontent.com/darrylcauldwell/meWeb/main/scripts/deploy-droplet.sh \
#     | bash -s -- [SITE_ADDRESS] [ACME_EMAIL] [REPO_URL]
#
# All arguments are optional - sensible defaults are baked in.
# Override any value by passing positional arguments.
#
# Idempotent - safe to re-run on an already-provisioned droplet.
# Tested on Ubuntu 22.04 / 24.04.
# =============================================================================

DEPLOY_DIR="/opt/meWeb"

usage() {
  cat <<EOF
Usage: deploy-droplet.sh [SITE_ADDRESS] [ACME_EMAIL] [REPO_URL]

  SITE_ADDRESS  Domain name         (default: blog.dreamfold.dev)
  ACME_EMAIL    Let's Encrypt email (default: darrylcauldwell@users.noreply.github.com)
  REPO_URL      Git clone URL       (default: https://github.com/darrylcauldwell/meWeb.git)

All arguments are optional. Run with --help to see this message.
EOF
  exit 0
}

log() {
  echo "[deploy] $*"
}

# ---------------------------------------------------------------------------
# 1. Resolve inputs (defaults baked in, overridable via positional args)
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
fi

SITE_ADDRESS="${1:-blog.dreamfold.dev}"
ACME_EMAIL="${2:-darrylcauldwell@users.noreply.github.com}"
REPO_URL="${3:-https://github.com/darrylcauldwell/meWeb.git}"

log "SITE_ADDRESS = $SITE_ADDRESS"
log "ACME_EMAIL   = $ACME_EMAIL"
log "REPO_URL     = $REPO_URL"

# ---------------------------------------------------------------------------
# 2. Install Docker
# ---------------------------------------------------------------------------
log "Installing Docker and Docker Compose plugin..."
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-v2

# ---------------------------------------------------------------------------
# 3. Enable Docker
# ---------------------------------------------------------------------------
log "Enabling Docker service..."
systemctl enable --now docker

# ---------------------------------------------------------------------------
# 4. Configure firewall
# ---------------------------------------------------------------------------
log "Configuring firewall..."
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable
log "Firewall status:"
ufw status

# ---------------------------------------------------------------------------
# 5. Clone repo (or pull if already present)
# ---------------------------------------------------------------------------
if [[ -d "$DEPLOY_DIR/.git" ]]; then
  log "Repository already exists at $DEPLOY_DIR, pulling latest changes..."
  git -C "$DEPLOY_DIR" pull
else
  log "Cloning repository into $DEPLOY_DIR..."
  git clone "$REPO_URL" "$DEPLOY_DIR"
fi

# ---------------------------------------------------------------------------
# 6. Write .env
# ---------------------------------------------------------------------------
ENV_FILE="$DEPLOY_DIR/site/.env"
log "Writing $ENV_FILE..."
PLANESPOTTER_DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 24)
EVM_DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 24)
EVM_SECRET_KEY=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 48)
cat > "$ENV_FILE" <<ENVEOF
# Generated by deploy-droplet.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit these values to suit your deployment.

SITE_ADDRESS=${SITE_ADDRESS}
ACME_EMAIL=${ACME_EMAIL}
GITHUB_USER=darrylcauldwell
NTFY_ADDRESS=ntfy.dreamfold.dev
NTFY_URL=https://ntfy.dreamfold.dev

# Planespotter
PLANESPOTTER_ADDRESS=planespotter.dreamfold.dev
PLANESPOTTER_DB_PASSWORD=${PLANESPOTTER_DB_PASSWORD}
PLANESPOTTER_API_URL=http://planespotter-api:8000

# Equestrian Venue Manager
EVM_ADDRESS=evm.dreamfold.dev
EVM_DB_USER=evm
EVM_DB_PASSWORD=${EVM_DB_PASSWORD}
EVM_DB_NAME=evm_db
EVM_SECRET_KEY=${EVM_SECRET_KEY}
EVM_ACCESS_TOKEN_EXPIRE=30
EVM_REFRESH_TOKEN_EXPIRE=7
EVM_STRIPE_SECRET_KEY=
EVM_STRIPE_WEBHOOK_SECRET=
ENVEOF

# ---------------------------------------------------------------------------
# 7. Start the production stack
# ---------------------------------------------------------------------------
log "Starting production stack..."
cd "$DEPLOY_DIR/site"
docker compose -f docker-compose.production.yml up -d --build

# ---------------------------------------------------------------------------
# 8. Wait for database initialization
# ---------------------------------------------------------------------------
log "Waiting for Planespotter database to finish importing aircraft data..."
log "(This can take 2-5 minutes on first run)"

# Wait for planespotter-db to be healthy and import to complete
MAX_WAIT=300
WAITED=0
while [[ $WAITED -lt $MAX_WAIT ]]; do
  # Check if the database container is done initializing by looking for the ready message
  if docker logs planespotter-db 2>&1 | grep -q "database system is ready to accept connections" && \
     docker exec planespotter-db pg_isready -U postgres > /dev/null 2>&1; then
    # Also check if the import script has finished (no more active COPY operations)
    ACTIVE=$(docker exec planespotter-db psql -U postgres -tAc "SELECT count(*) FROM pg_stat_activity WHERE query LIKE 'COPY%';" 2>/dev/null || echo "1")
    if [[ "$ACTIVE" == "0" ]]; then
      log "Planespotter database ready."
      break
    fi
  fi
  sleep 5
  WAITED=$((WAITED + 5))
  log "Still waiting... (${WAITED}s)"
done

if [[ $WAITED -ge $MAX_WAIT ]]; then
  log "Warning: Timed out waiting for database. It may still be initializing."
fi

# Restart planespotter-api to ensure it connects after DB is ready
log "Restarting Planespotter API to connect to database..."
docker restart planespotter-api
sleep 5

# ---------------------------------------------------------------------------
# 9. Seed EVM with demo data
# ---------------------------------------------------------------------------
log "Seeding EVM database with demo data..."
docker compose -f docker-compose.production.yml --profile seed up evm-seed
log "EVM seeding complete."

# ---------------------------------------------------------------------------
# 10. Verify
# ---------------------------------------------------------------------------
log "Waiting for containers to stabilize..."
sleep 5

log "Container status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

# Check health endpoint (allow failure - cert may not be ready yet)
log "Checking health endpoint..."
if curl -sf --max-time 10 "http://localhost/healthz" > /dev/null 2>&1; then
  log "Health check passed."
else
  log "Health endpoint not yet reachable (this is normal if DNS is not configured yet)."
fi

# ---------------------------------------------------------------------------
# 11. Next steps
# ---------------------------------------------------------------------------
cat <<EOF

========================================
  Deployment complete!
========================================

Next steps:

  1. Ensure DNS A records point to this droplet's IP address:
       - ${SITE_ADDRESS}
       - ntfy.dreamfold.dev
       - planespotter.dreamfold.dev
       - evm.dreamfold.dev

  2. Once DNS propagates, Caddy will automatically obtain TLS certificates.
     Monitor certificate acquisition with:

       docker logs site

  3. Verify the site is live:

       curl -I https://${SITE_ADDRESS}
       curl https://${SITE_ADDRESS}/healthz
       curl -I https://ntfy.dreamfold.dev
       curl https://planespotter.dreamfold.dev/healthz
       curl https://evm.dreamfold.dev/healthz

  4. To update later:

       cd ${DEPLOY_DIR}/site
       git pull && docker compose -f docker-compose.production.yml up -d --build

EOF
